### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by bojanz** [cockroachdb/apd#113]
Just wanted to say thank you for the v3 release. The performance improvements are noticeable.

[Benchmarks](https://gist.github.com/bojanz/eda3c0d6fdc1db16aff0a964121686eb) from my package (bojanz/currency) where the average coefficient is small:

Results for apd v2:
```
BenchmarkAdd-12       	 2718600	       435.0 ns/op	     128 B/op	       3 allocs/op
BenchmarkSub-12       	 3016879	       405.6 ns/op	      88 B/op	       3 allocs/op
BenchmarkMul-12       	 1447600	       820.8 ns/op	     168 B/op	       5 allocs/op
BenchmarkMulDec-12       1000000	      1055 ns/op	     184 B/op	       7 allocs/op
BenchmarkDiv-12       	  465312	      2928 ns/op	     336 B/op	      11 allocs/op
BenchmarkDivDec-12    	  355858	      3116 ns/op	     352 B/op	      13 allocs/op
BenchmarkRound-12     	  870912	      1228 ns/op	     296 B/op	      11 allocs/op
BenchmarkCmp-12       	85437470	        15.05 ns/op	       0 B/op	       0 allocs/op
```

Results for apd v3:
```
BenchmarkAdd-12       	 4333795	       286.2 ns/op	      64 B/op	       2 allocs/op
BenchmarkSub-12       	 4126153	       298.8 ns/op	      64 B/op	       2 allocs/op
BenchmarkMul-12       	 1990543	       625.5 ns/op	      96 B/op	       3 allocs/op
BenchmarkMulDec-12      1366653	       863.4 ns/op	     112 B/op	       5 allocs/op
BenchmarkDiv-12       	  627897	      1614 ns/op	      96 B/op	       3 allocs/op
BenchmarkDivDec-12    	  889832	      1317 ns/op	     112 B/op	       5 allocs/op
BenchmarkRound-12     	 2020036	       574.0 ns/op	      64 B/op	       2 allocs/op
BenchmarkCmp-12       	84142538	        14.26 ns/op	       0 B/op	       0 allocs/op
```

**Comment by nvanbenschoten** [comment]
Hi @bojanz, thank you for the kind words and for posting those benchmark results! We're happy to hear that this library is in use in https://github.com/bojanz/currency and that the recent performance improvements made a noticeable difference.

**Comment by nvanbenschoten** [comment]
By the way, https://github.com/bojanz/currency looks like a very nice library. I noticed that the `Amount` data type is represented like:
```go
type Amount struct {
	number       *apd.Decimal
	currencyCode string
}
```

Out of curiosity, did you ever try storing the `number` field by value in the `Amount` struct? Something like:
```go
type Amount struct {
	number       apd.Decimal
	currencyCode string
}
```

**Comment by bojanz** [comment]
@nvanbenschoten 
Thanks for taking a look, appreciated.

I used *apd.Decimal because that's what apd.NewFromString(n) gives me, so I assumed a reference was preferred. If that's not the case, I can give the value a shot, since the number is private we can modify it without a BC break.

Also, is there a reason why you extracted:
```
var (
	decimalContextPrecision39 = apd.BaseContext.WithPrecision(39)
	decimalContextPrecision19 = apd.BaseContext.WithPrecision(19)
)
```
from decimalContext()?

**Comment by nvanbenschoten** [comment]
> I used *apd.Decimal because that's what apd.NewFromString(n) gives me, so I assumed a reference was preferred.

The zero value of `apd.Decimal` is usable, so the type can be used by value. This can avoid heap allocations and memory indirection.

> Also, is there a reason why you extracted ... from decimalContext()?

Each call to `apd.BaseContext.WithPrecision` was performing a heap allocation, so statically creating these decimal contexts should reduce the cost of `decimalContext`.

**Comment by bojanz** [comment]
@nvanbenschoten 
Understood. Did some cleanup to reduce diff size, committed the fixes, tagged a release. Thank you once again!
