### ISSUE TITLE
please drop github.com/pkg/errors

### ISSUE THREAD

**Issue by mvdan** [cockroachdb/apd#123]
Now that the standard library's errors package supports wrapping errors in a... standard way :) There shouldn't be a need to use pkg/errors anymore.

This has the advantage that the library will have zero dependencies, which is nice!

I can try to send a patch, though I don't know what formatting style the errors are meant to follow in this project, so it might be easiest for one of the maintainers or developers to do it directly. Calls to `New` and `Errorf` should be the same, and calls to `Wrap` can be replaced with `Errorf("some message: %w", err)`.

**Comment by mvdan** [comment]
A clarification: you might not end up with zero module dependencies, because lib/pq is still a test dependency. I think you should also bump your `go.mod` to say `go 1.17` and run `go mod tidy`.

**Comment by nvanbenschoten** [comment]
@mvdan I just published a new release that includes #124: https://github.com/cockroachdb/apd/releases/tag/v3.1.1.
