### ISSUE TITLE
accommodating > int128 

### ISSUE THREAD

**Issue by academe-01** [cockroachdb/apd#135]
Hello,
1. what if I need to inline int256 values, can I just increase `bigint.go:28 const inlineWords` to 256 ?
Or it can break some logic ?

2. why if apd.NewBigInt(-1) set to negative, it will create _inner big.Int anyways ? -1 definitely fits into announced int128

**Comment by nvanbenschoten** [comment]
Hi @academe-01,

> what if I need to inline int256 values, can I just increase bigint.go:28 const inlineWords to 256 ?
Or it can break some logic ?

I'm not aware of any reasons why this shouldn't work. Want to give it a try and see if the tests all pass?

> why if apd.NewBigInt(-1) set to negative, it will create _inner big.Int anyways ? -1 definitely fits into announced int128

Is is set to the `negSentinel` value?
https://github.com/cockroachdb/apd/blob/1ebf5456448c80c7d15d3e5043f8087e38fa0182/bigint.go#L70-L73
