### ISSUE TITLE
TestFormatFlags fails on Go1.23

### ISSUE THREAD

**Issue by zhsj** [cockroachdb/apd#138]
```
--- FAIL: TestFormatFlags (0.00s)
    --- FAIL: TestFormatFlags/1.23E+56:_%-010G (0.00s)
        decimal_test.go:592: expected "1.23E+56  ", got "001.23E+56"
FAIL
```

**Comment by nvanbenschoten** [comment]
The case that is breaking is `fmt.Sprintf("e%-010G", d)`.

This seems to be fallout from https://github.com/golang/go/issues/61784 / https://github.com/golang/go/commit/6dfd7a543517db868ef4f31e91fe56aba5bc8ea0. Previously, the "pad with leading zeros" flag was ignored. In go1.23 and after, it is not.
