### ISSUE TITLE
Investigate Newton–Raphson for Quo

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/apd#22]
See https://github.com/cockroachdb/apd/issues/13#issuecomment-280407542

**Comment by mjibson** [comment]
This is difficult because this method uses successive approximation, which makes it difficult to determine exactness. That is, the current long division method maintains a remainder which can be used to know if the division was exact or not. I'm not sure how Newton-Raphson could correctly report exactness.

@eisenstatdavid

**Comment by eisenstatdavid** [comment]
I'll take a crack at this when I have time.

**Comment by mjibson** [comment]
I tried real hard to make this work but couldn't. Some code linked in those PRs.
