### ISSUE TITLE
How to round up to fixed number of decimal digits?

### ISSUE THREAD

**Issue by TamalSaha** [cockroachdb/apd#50]
Thanks for this great library. I am trying to use this lib in financial calculation. I am doing all my intermediate calculations with high precision but I want to store the final result with 2 decimal digits (RoundHalfUp if needed). How do I do that? 

```
d1 := apd.New(5, 0)
d2 := apd.New(3, 0)
r := apd.New(0, 0)
c := apd.BaseContext.WithPrecision(30)
res, err := c.Quo(r, d1, d2)
```

Now, I want to get `1.67` as the final answer from `r` . How do I do that?

**Comment by mjibson** [comment]
You can use `Quantize` to do this. See the examples: https://godoc.org/github.com/cockroachdb/apd#example-Context-Quantize

**Comment by TamalSaha** [comment]
Exactly what I was looking for. Thanks!
