### ISSUE TITLE
Should Quatize() work with 0 precision?

### ISSUE THREAD

**Issue by TamalSaha** [cockroachdb/apd#51]
https://github.com/cockroachdb/apd/blob/master/context.go#L1154
```
	res := c.quantize(d, x, exp)
	if nd := d.NumDigits(); nd > int64(c.Precision) || exp > c.MaxExponent {
		res = InvalidOperation
		d.Set(decimalNaN)
	} else {

```
This results in `NaN` if precision is not set. Is this expected?

**Comment by mjibson** [comment]
Yes, it is expected. The precision must be >= the number of digits being returned. (This needs to be documented).
