### ISSUE TITLE
ToStandard is missing

### ISSUE THREAD

**Issue by cristian-sima** [cockroachdb/apd#62]
Hi. 

I am using this package https://github.com/leekchan/accounting which uses in turn your package. It seems you've removed `ToStandard`. 

```
github.com/leekchan/accounting
../../leekchan/accounting/formatnumber.go:79: d.ToStandard undefined (type *apd.Decimal has no field or method ToStandard)
../../leekchan/accounting/formatnumber.go:139: d.ToStandard undefined (type *apd.Decimal has no field or method ToStandard)
```
Can you tell me which is its equivalent?

Thanks

https://github.com/leekchan/accounting/issues/6

**Comment by mjibson** [comment]
It's listed in the commit (https://github.com/cockroachdb/apd/commit/72773d4868113f0e0d5acce735fd492c06296e3b): `.Text('f')` should do it.

**Comment by cristian-sima** [comment]
Thanks mate. The developer has solved this
