### ISSUE TITLE
rfc: release tags

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/apd#73]
I am planning on making tagged releases of apd for better version control. The plan is to:

1. Make a tag of `v1.0.0` as the first release, since I consider apd to be in very good shape and am confident that tagging it as a 1.0 is safe.
1. NOT make a new branch, just stick with tags and develop on master.
1. Make new releases with more-or-less each commit. This is because I don't expect there to be many commits. The minor version will be incremented on any additional feature, API addition, performance gain. Patch version on any bug, doc change, correctness issue, etc. I don't expect to increment the major version much. I suppose on major API changes like if we decide ErrDecimal is silly and needs to change.

Comments? @RaduBerinde @nvanbenschoten

**Comment by RaduBerinde** [comment]
Sounds good to me!

**Comment by nvanbenschoten** [comment]
Yeah, adhering to [semantic versioning](http://semver.org/) sounds good to me too.

**Comment by mjibson** [comment]
Great. Done.
