### ISSUE TITLE
Proper way to set a apd.NullDecimal?

### ISSUE THREAD

**Issue by caseylmanus** [cockroachdb/apd#75]
The types on https://gopkg.in/nullbio/null.v6 implement a SetValid method, which maybe useful for NullDecimal.  Otherwise, how should you set the value of NullDecimal?

**Comment by mjibson** [comment]
None of the types in https://golang.org/pkg/database/sql/#NullFloat64 have a SetValid method, and I'm not inclined to differ from the standard library without a really good use case.

**Comment by caseylmanus** [comment]
So what is the recommended way to set the value?

**Comment by mjibson** [comment]
```
var nd *apd.NullDecimal
nd.Valid = true
vd.Decimal = d
```

**Comment by caseylmanus** [comment]
Although I agree with being inline with the standard library, seems like we could improve the API by adding 

`
func (n *apd.NullDecimal) SetValid(d apd.Decimal) {
    n.Decimal = d
    n.Valid = true
}
`

**Comment by mjibson** [comment]
Yes, that's possible, but I think we'll leave the API as is for now. I'll file this in my head with the few other NullDecimal things (like json marshalling) and if there are enough we can flesh out the type more. Part of me wants to just remove it altogether because it almost doesn't belong here.

**Comment by caseylmanus** [comment]
Please consider this, and adding JSON support, more importantly even.  I didn't realize that was missing until you mentioned it.  

https://gist.github.com/caseylmanus/6ace6cb449f35d4e679b37b3bb0765b7

I'd make a branch and submit a pull request if you'd accept this code.

**Comment by mjibson** [comment]
See the discussion in https://github.com/cockroachdb/apd/pull/68 for why json support isn't included for NullDecimal.

**Comment by caseylmanus** [comment]
Matt, 

I'm certainly not one to beat a dead horse, and if your final answer is no that makes sense, but for my use case NaN and Infinity should just generate an err in json marshalling because they aren't really valid values in any context that json would be acceptable for (I think, maybe I am wrong).  I suspect that like me, a good number of the people using a decimal library in Go are using it because float isn't acceptable for money and financial applications.  To that end, I've written some simple unit tests against my changes. 

https://gist.github.com/caseylmanus/f38cca05d59a89469b53460639484bbf

**Comment by mjibson** [comment]
My requirement for adding a marshal/unmarshal method is that they be 100% round-trippable. See my comment from that thread about big.Float, for example, which does support Infinity and text/json marshalling, but doesn't marshal as a number for that and other reasons. Also consider that javascript numbers don't map correctly (they lose precision) when numbers get even kind of large, so a apd.Decimal -> javascript number conversion is really problematic. Hence our use of strings instead.

If you as a user of apd.Decimal know exactly how your data will be used on the other side and are comfortable with lossy javascript numbers, then you are free to add whatever methods you want to do that conversion. It's pretty easy to make your own type that's a wrapper around apd.Decimal or NullDecimal with the marshal or whatever methods. But this package's goals are to always work correctly, and I haven't seen any code yet that does for NullDecimal or JSON numbers.

**Comment by caseylmanus** [comment]
Understood, I'll close the issue.  Thanks for the detailed response and a
great discussion.
