### ISSUE TITLE
request for new tag

### ISSUE THREAD

**Issue by kardianos** [cockroachdb/apd#86]
Hey, I just saw you've tagged a v2 release, but the tag doesn't have the v2 in the go mod path.
https://github.com/cockroachdb/apd/blob/v2.0.0/go.mod

Would you mind issuing a point release? Thanks, -Daniel

**Comment by mjibson** [comment]
I think I've done this now? Still unsure how all this works.

**Comment by kardianos** [comment]
Nice. That should work. I'll test in a bit, but should be fine.
