### ISSUE TITLE
Function remainder returns division impossible

### ISSUE THREAD

**Issue by tredoe** [cockroachdb/apd#87]
```
package main

import (
	"log"

	apd "github.com/cockroachdb/apd/v2"
)

func main() {
	dec("4", "2")
}

func dec(x, y string) {
	rem := new(apd.Decimal)

	valx, _, err := apd.NewFromString(x)
	if err != nil {
		panic("x: " + err.Error())
	}
	valy, _, err := apd.NewFromString(y)
	if err != nil {
		panic("y: " + err.Error())
	}

	_, err = apd.BaseContext.Rem(rem, valx, valy)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("result: %s", rem)
}
```

**Comment by mjibson** [comment]
The BaseContext has a precision of 0, so division will fail because there's not enough room to put the remainder. See the documentation on [Rem](https://godoc.org/github.com/cockroachdb/apd#Context.Rem):

> Rem sets d to the remainder part of the quotient x/y. If the integer part cannot fit in d.Precision digits, an error is returned.

**Comment by mjibson** [comment]
You can do `BaseContext.WithPrecision(1).Rem(...)` for example.
