### ISSUE TITLE
Cbrt not being tested

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/apd#9]
`Cbrt` is not being tested, despite having a test file for cuberoot.

 I can add a `return 0, nil` at the beginning and the tests pass..

```
 func (c *Context) Cbrt(d, x *Decimal) (Condition, error) {
+	return 0, nil
```

```
    --- PASS: TestParseDecTest/cuberoot-apd.decTest (0.00s)
```

```
go test
PASS
ok  	github.com/cockroachdb/apd	4.267s
```

**Comment by mjibson** [comment]
Ah, this was removed inadvertently in 93be6be300c0075a4758ea2a6fd28983f663e5f1. Adding that file back, though, now fails because of the change in a1105927ff9cad78620625c626330c6f1378eba1. Looking into it more.
