### ISSUE TITLE
format weirdness with a non-pointer Decimal

### ISSUE THREAD

**Issue by borovan** [cockroachdb/apd#90]
Sorry first time I've done this!

Basically, if you've got the code

`	
var a1 apd.Decimal

a1.Scan(234.234)

log.Printf("%f", a1)

var a2 *apd.Decimal

a2, _, _ = apd.NewFromString("345.345")

log.Printf("%s", a2)
`

it prints out :

2019/04/14 18:07:55 {%!f(apd.Form=0) %!f(bool=false) %!f(int32=-3) {%!f(bool=false) [%!f(big.Word=234234)]}}
2019/04/14 18:07:55 345.345

This behaviour was weird enough for me to write a wrapper around it.   Sorry I fail at markdown

I believe it can be fixed by removing the pointer from the receiver of the Format() function call

**Comment by mjibson** [comment]
This is a known behavior. Our API was modeled from the big.Int package, whose [String() method](https://golang.org/pkg/math/big/#Int.String) is also defined on a pointer type, and which thus would act the same. Unless there's a compelling argument to differ from what the standard library does for similar types, I'm not inclined to change this.

**Comment by borovan** [comment]
Ok cool, not a problem, thanks for clearing that up.

I'm writing an ORM right now and have seen that pointers are used for nullable fields.  So like in GORM it's time.Time (CreatedAt, not null) vs. *time.Time (DeletedAt, nullable).  I use apd.Decimal for my decimal type but since you instantiate it as a pointer was just getting this weird behaviour when I fmt.Sprintf the values.

Anyway I wrap all the third party types now so I just did this :

```
func (d Decimal) Format(s fmt.State, format rune) {
	d.Decimal.Format(s, format)
}

// Cmp wrapper
func (d Decimal) Cmp(x Decimal) int {
	return d.Decimal.Cmp(&x.Decimal)
}
```

**Comment by mjibson** [comment]
Just add `.String()` to everything and you'll be safe no matter if it's a pointer or not.
