### ISSUE TITLE
Inconsistent behaviour for negative zero

### ISSUE THREAD

**Issue by djui** [cockroachdb/apd#91]
```go
d1 := apd.New(-0, 0)
fmt.Println(d1) // "0"

d2, _, _ := apd.NewFromString("-0")
fmt.Println(d2) // "-0"
```

**Comment by mjibson** [comment]
`-0` as a numeric literal in go is always converted to `0`: https://play.golang.org/p/o_MH6eIUkgP

**Comment by djui** [comment]
Understood. Should the NewFromString then adjusted to be the same or is ok to have them slightly different? I guess parsing and modifying afterwards is not good either.

Maybe that’s just how it is. Will close.

**Comment by mjibson** [comment]
I think things are ok as is. *If* APD gets a `-0` it will keep it, but it's just hard to do that in Go.
