### ISSUE TITLE
precision, scale 

### ISSUE THREAD

**Issue by samstride** [cockroachdb/apd#99]
Firstly, thank you for making this library available.

We use CRDB as our data store and this library when we need to do decimal operations.

Following taken from CRDB docs:

```sh
DECIMAL(precision, scale), where precision is the maximum count of digits both to the left and right of the decimal point 
and scale is the exact count of digits to the right of the decimal point.
.
.
.
When inserting a decimal value:

If digits to the right of the decimal point exceed the column's scale, CockroachDB rounds to the scale.
If digits to the right of the decimal point are fewer than the column's scale, CockroachDB pads to the scale with 0s.
```

What is the best way to achieve CRDB's `precision, scale` with apd v2? An example would be handy.

What is the best way to round digits to the right of the decimal point with apd v2 ? An example would be handy.

**Comment by samstride** [comment]
@mjibson , are you able to help with this issue?

**Comment by mjibson** [comment]
https://github.com/cockroachdb/cockroach/blob/8187c2551352a6c28eba021effaebcbfe523d78c/pkg/sql/sem/tree/decimal.go#L58 is how cockroach does this.

**Comment by samstride** [comment]
@mjibson , thanks will have a look.

**Comment by samstride** [comment]
@mjibson , I put this together - [https://play.golang.org/p/Skm023JrE3U](https://play.golang.org/p/Skm023JrE3U)

Seems to be working. Let me know if I got something wrong?

Also, I feel it would be useful to have that `LimitDecimalWidth` feature in apd v2 itself. What are your thoughts on this? I am happy to submit a PR if I can get some guidance.

Once again, thanks for helping out.

**Comment by mjibson** [comment]
apd is well-scoped to be whatever http://speleotrove.com/decimal/ provides and tries really hard to not do more things. That function is possible useful as a documented example instead of an included function. However I no longer have merge permission to this repo so am unable to help out too much making that happen beyond reviewing a PR.

**Comment by samstride** [comment]
@mjibson , Thanks. I guess if someone ever uses `apd v2` and wants to achieve `precision,scale`, the information in this conversation should help them.
